# Cloudflare Workers/Pages設定ファイル
# サテライト投資管理アプリ用
# Agent 2 - Phase 1-4: 完全なWorkers設定

name = "satellite-investment-app"
compatibility_date = "2025-08-10"
compatibility_flags = ["nodejs_compat"]

# アカウント設定（実際のデプロイ時に設定）
# account_id = "your-account-id-here"

# Pages Functions設定
pages_build_output_dir = "_dist"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "satellite-investment-db"
database_id = "your-database-id-here" # wrangler d1 create で取得したIDを設定

# 本番用D1設定（別データベース）
[[env.production.d1_databases]]
binding = "DB"
database_name = "satellite-investment-db-prod"
database_id = "your-prod-database-id-here"  # 実際のデプロイ時に更新が必要

# Cron Triggers設定
[[triggers.crons]]
cron = "0 5 * * *"  # 毎日AM5:00（UTC）
timezone = "Asia/Tokyo"  # 日本時間

# 環境変数設定
[vars]
API_VERSION = "1.0.0"
APP_NAME = "Satellite Investment Manager"
TYPE_SYSTEM_VERSION = "1.3.0"

# 本番環境変数
[env.production.vars]
ENVIRONMENT = "production"
DEBUG_MODE = "false"
LOG_LEVEL = "warn"

# プレビュー環境変数
[env.preview.vars]
ENVIRONMENT = "preview"
DEBUG_MODE = "true"
LOG_LEVEL = "info"

# 開発環境変数（ローカル）
[env.development.vars]
ENVIRONMENT = "development"
DEBUG_MODE = "true"
LOG_LEVEL = "debug"

# ビルド設定
[build]
command = "npm run build:deploy"
cwd = "."
watch_dir = ["src", "pages", "public", "styles"]

# リソース制限
[limits]
cpu_ms = 50  # CPU実行時間制限（ミリ秒）

# Pages設定
[pages]
# カスタムドメイン設定（オプション）
# custom_domain = "your-custom-domain.com"

# セキュリティヘッダー
[[pages.headers]]
for = "/*"

[pages.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.example.com;"

# キャッシュ設定
[[pages.headers]]
for = "/api/*"

[pages.headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[pages.headers]]
for = "/*.js"

[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.css"

[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# リダイレクト設定
[[pages.redirects]]
from = "/admin"
to = "/"
status = 301

# Functions設定
[pages.functions]
# Functions のディレクトリ（デフォルト: functions/）
directory = "pages/api"

# 互換性設定
[pages.functions.compatibility]
nodejs_compat = true

# Node.js互換性フラグ
[pages.functions.compatibility_flags]
nodejs_compat = true